---
title: "Software Helpfile"
author: "Hannah M Carroll"
date: "September 12, 2019"
output: word_document
---

### Supplementary Information - Software Helpfile

The authors claim no affiliation with or authorship of any software package used in these exercises. The information below is provided solely to assist those new to teaching in R/RStudio.

---

## Optional: Signularity Container

The Singularity container provided with this module is a small, self-contained OS image which hosts all required software packages in the appropriate versions, and all R package dependencies (additional packages required by packages being installed by the user). It is operating system agnostic and ensures that each student and instructor is using exactly the same computing environment on which this exercise was developed and tested. For most institutions, your IT department must implement the Singularity container. This is optional, but eliminates concerns over compatibility.

Find the Singularity user guide here: https://sylabs.io/guides/3.3/user-guide/ 

---

## Software Requirements

# Introductory exercise:
R Version 3.5.1 or later  
RStudio Version 1.1.456 or later  

**R packages**  
readxl 1.1.0  
ggplot2 3.2.0  
cluster 2.0.7.1  
factoextra 1.0.5  
tRophicPosition 0.7.7  
viridis 0.5.1  

# Advanced exercise:
R Version 3.5.1 or later  
RStudio Version 1.1.456 or later  
JAGS version 4.3.0 or later  

**R packages**  
rjags 4.8  
simmr 0.4.1  
dplyr 0.8.2  
ggplot2 3.2.0  

- Note: Some versions of R may produce an error during package installation stating that the package rtools must be installed. This message can be ignored.

---

## Installation

Each exercise contains code to install the R packages for that exercise. This may take a substantial amount of time. In particular, dplyr installation can take up to an hour or more on slow connections. If this is a concern, please ensure that dplyr has been pre-installed on each machine on which these exercises are to be used. The code will check for and skip installation of any packages which are already installed.

---
## Tested versions

These exercises were tested on R versions 3.5.1 (Windows) and 3.6.2 (Windows and Mac), and RStudio versions 1.1.456 and 1.2.1335 (Windows), using the package versions listed above as the minimum required. JAGS version 4.3.0 was tested on Windows and Mac. Commands are written as simply as possible to ensure compatibility with future versions.

---

## JAGS vs rjags

JAGS (Just Another Gibbs Sampler) is a standalone software program which was developed to analyze Bayesian hierarchical models using Markov Chain Monte Carlo (MCMC) simulation. It must be installed on each computer on which the *advanced* exercise will be used. It is not needed for the introductory exercise. The R package rjags is your interface to JAGS. Package rjags solves isotope mixing models using the framework provided by JAGS. The exercise has been tested on JAGS version 4.3.0 using rjags version 4.8. Find the JAGS readme at http://mcmc-jags.sourceforge.net/ and rjags documentation at https://cran.r-project.org/web/packages/rjags/rjags.pdf

---

## Contact information

Bug reports should be submitted to Hannah Carroll via e-mail at carroll.hannah.m@gmail.com or via a GitHub issue report at the project repository: https://github.com/hannahcarroll/Aquatic-isotopes
